apiVersion: v1
kind: Secret
metadata:
  name: {{ include "valera.fullname" . }}
  labels:
    {{- include "valera.labels" . | nindent 4 }}
type: Opaque
stringData:
  TELEGRAM_API_TOKEN: {{ .Values.bot.telegramToken | quote }}
  REDIS_URL: {{ tpl .Values.bot.redisUrl . | quote }}
  REDIS_PASSWORD: {{ .Values.bot.redisPassword | quote }}
