replicaCount: 1

image:
  pullPolicy: IfNotPresent
  tag: "0.0.1"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
podLabels: {}

resources: {}

nodeSelector: {}
tolerations: []
affinity: {}

redis:
  auth:
    enabled: true
    existingSecret: valera
    existingSecretPasswordKey: REDIS_PASSWORD
  master:
    persistence:
      enabled: true
  replica:
    replicaCount: 0
